version: '2.2'

services:
  moderationapiapp:
    image: moderationapi
    container_name: moderationapiapp
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 5050:8080
    networks:
      - moderationbridgenetwork
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - moderationbridgenetwork
    volumes:
      - mymongovolume:/data/db
      - mymongovolume:/data/configdb
    restart: always

  

networks:
  moderationbridgenetwork:
    driver: bridge

volumes:
  mymongovolume:
