version: '2.2'

services:
  moderationapiapp:
    image: moderationapi
    container_name: moderationapiapp
    depends_on:
      - moderationmongodb
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 5050:8080
    networks:
      - moderationbridgenetwork
    restart: always


  

networks:
  moderationbridgenetwork:
    name: exercises-api_mongobridgenetwork 
    external: true

volumes:
  mymongovolume:
